### ISSUE TITLE
utils folder missing 

### ISSUE THREAD

**Issue by lingjieyi** [imics-lab/tts-gan#1]
When I ran the code following the instruction, I got the below error:

Traceback (most recent call last):
  File "train_GAN.py", line 10, in <module>
    from functions import train, train_d, validate, save_samples, LinearLrDecay, load_params, copy_params, cur_stages
  File ".......\TTS-GAN A Transformer-based Time-Series Generative Adversarial Network\functions.py", line 16, in <module>
    from utils.utils import make_grid, save_image
ModuleNotFoundError: No module named 'utils'

Can you please advice?

**Comment by Xiaomin-Li** [comment]
Hi, thanks for bringing that up. I have added the utils folder. Also, the code is converted from this repo: https://github.com/VITA-Group/TransGAN   You may take a look for more information.

**Comment by lingjieyi** [comment]
Great. Thanks for the quick response!

Appreciate!

Best,
Chris

Xiaomin ***@***.***>于2022年3月11日 周五上午7:56写道：
