### ISSUE TITLE
can't download the datasets

### ISSUE THREAD

**Issue by Yangsenqiao** [imics-lab/tts-gan#2]
I am sorry to tell you the link:https://www.dropbox.com/s/raw/x2fpfqj0bpf8ep6/UniMiB-SHAR.zip is not work.

**Comment by Xiaomin-Li** [comment]
From my side, I can download the dataset from this link. That's odd. Maybe you can try to download the dataset from their official website: http://www.sal.disco.unimib.it/technologies/unimib-shar/

**Comment by Yangsenqiao** [comment]
I’ll try it. Thanks a lot.

从 Windows 版邮件发送

发件人: Xiaomin
发送时间: 2022年5月16日 0:07
收件人: imics-lab/tts-gan
抄送: Yangsenqiao; Author
主题: Re: [imics-lab/tts-gan] can't download the datasets (Issue #2)

From my side, I can download the dataset from this link. That's odd. Maybe you can try to download the dataset from their official website: http://www.sal.disco.unimib.it/technologies/unimib-shar/

**Comment by stillwang96** [comment]
Hi, I have met the same problem here, have you ever solved it?
