### ISSUE TITLE
Folder naming "pre-trained-models"

### ISSUE THREAD

**Issue by nandvar** [imics-lab/tts-gan#3]
LoadSyntheticRunningJumping.py

```
12    Jumping_model_path = './pre-trained-model/JumpingGAN_checkpoint',
13    Running_model_path = './pre-trained-model/RunningGAN_checkpoint',
```

reffering to the folder as "pre-trained-model" instead of "pre-trained-models"

**Comment by Xiaomin-Li** [comment]
Thanks for reminding me. I have fixed the folder naming issue.
