### ISSUE TITLE
Request for an e-mail address

### ISSUE THREAD

**Issue by stillwang96** [imics-lab/tts-gan#5]
Hello,  I have been reading your papers TTS-GAN and TTS-CGAN recently, and I am very interested in your research. I am trying to run your codes, but I have encountered some small problems and would like to ask you. I tried to send an e-mail to you, but it always fails, so may I have your new e-mail address? It couldn't be better if it is an adress in China, Thank you.

**Comment by Xiaomin-Li** [comment]
Hi, thanks for being interested in my work. My school email is x_l30@txstate.edu (The third character is lowercase 'L' not digit number 1). And you can try my Gmail account, lixiaomin170@gmail.com
